---

# nvim config root
- name: nvim config root
  shell: "curl -sLf https://spacevim.org/install.sh | bash"
  changed_when: false

# nvim config user
- name: nvim config user
  shell: "curl -sLf https://spacevim.org/install.sh | bash"
  changed_when: false
  remote_user: "{{ normal_user }}"