---

- name: Clone CustomScripts
  git:
    repo: https://github.com/ramesh45345/CustomScripts
    dest: "{{ csfolder }}"
    clone: yes
    update: yes

# CCSClone.py
- name: CCSClone.py
  shell: "{{ csfolder }}/CCSClone.py"
  changed_when: false
