
- name: Add flathub repo
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install common flatpaks
  community.general.flatpak:
    name:
      - com.calibre_ebook.calibre
      - com.github.tchx84.Flatseal
      - info.smplayer.SMPlayer
      - io.github.flattool.Warehouse
      - org.atheme.audacious
      - org.kde.kclock
      - org.libreoffice.LibreOffice
      - org.videolan.VLC
    state: latest
